services:
  client:
    build: ./client
    ports:
      - "8080:80"
    environment:
      - VUE_APP_API_URL=http://localhost:3000
    env_file:
      - ./client/.env
    command: npm run serve
    depends_on:
      - api
    

  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    command: npm run server
