services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - main
    volumes:
      - ./lib/.nginx:/etc/nginx

  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./client/.env
    command: npm run serve
    
  main:
    container_name: main
    build: ./api/main
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./api/main/.env
    command: npm run server

  ntt:
    container_name: ntt
    build: ./api/ntt 
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./api/ntt/.env 
    command: npm run server
