services:
  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://localhost:3000
    env_file:
      - ./client/.env
    command: npm run serve
    
  api:
    container_name: api
    build: ./api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    command: npm run server
