export const artist = {
    gegeAkutami: {
        name: "Gege Akutami",
        description: "Gege Akutami is a rising star in the manga art world, known for her ethereal style and captivating character designs. With a passion for blending traditional Japanese art with modern manga techniques, Gege's work has garnered international acclaim.",
        manga: "Jujutsu Kaisen",
        src: "/shop/jjk",
        btntext: "View Gege's Collection",
        firstBoock: "img/jjkvol1.jpg",
        secondBoock: "img/jjkvol4.jpg",
    },
    kotoyama: {
        name: "Kotoyama",
        description: "Kotoyama is a master of atmosphere, known for his unique ability to capture the essence of the night in his work. In 'Call of the Night,' he combines moody visuals with captivating storytelling, creating a world that is both haunting and alluring, drawing readers into the mysteries of the dark.",
        manga: "Call Of Night",
        src: "/shop/jjk",
        btntext: "View Kotoyama's Collection",
        firstBoock: "img/convol1.jpg",
        secondBoock: "img/convol7.jpg",
    },    
    kōheiHorikoshi: {
        name: "Kōhei Horikoshi",
        description: "Kōhei Horikoshi has redefined modern manga with 'My Hero Academia,' creating a world where heroism is both an art and a lifestyle. His expressive characters and action-driven style have captivated readers worldwide, solidifying his place among the greats.",
        manga: "My Hero Academia",
        src: "/shop/mha",
        btntext: "View Kōhei's Collection",
        firstBoock: "img/mhavol1.jpg",
        secondBoock: "img/mhavol25.jpg",
    },
    atsushiOhkubo: {
        name: "Atsushi Ohkubo",
        description: "Atsushi Ohkubo is celebrated for his unique fusion of dark themes and vibrant visuals. With 'Fire Force,' he showcases a world of intense battles and intricate designs, captivating readers with his detailed artistry and imaginative storytelling.",
        manga: "Fire Force",
        src: "/shop/ff",
        btntext: "View Atsushi's Collection",
        firstBoock: "img/ffvol1.jpg",
        secondBoock: "img/ffvol2.jpg",
    },
    yuutoSuzuki :{
        name: "Yuuto Suzuki",
        description: "Yuuto Suzuki is a fresh talent in the manga world, bringing humor, action, and an engaging art style to 'Sakamoto Days.' Known for his ability to blend intense action sequences with comedic elements, his work has quickly resonated with fans around the globe.",
        manga: "Sakamoto Days",
        src: "/shop/sd",
        btntext: "View Yuuto's Collection",
        firstBoock: "img/sdvol15.jpg",
        secondBoock: "img/sdvol17.jpg",
    }
};
